document.writeln("<style type=\"text/css\">");
document.writeln("    .center{");
document.writeln("        width: 390px;");
document.writeln("        height: 310px;");
document.writeln("        position: fixed;");
document.writeln("        left:50%;");
document.writeln("        top:50%;");
document.writeln("        transform: translate(-50%,-50%);");
document.writeln("        /*display: none;*/");
document.writeln("        z-index:9999999;");
document.writeln("    }");
document.writeln("    .center img{");
document.writeln("        cursor:pointer;");
document.writeln("        width:100%;");
document.writeln("    }");
document.writeln("    .center .close_btn{");
document.writeln("        position: absolute;");
document.writeln("        right: 0;");
document.writeln("        top: 0;");
document.writeln("        /*background-color: #f00;*/");
document.writeln("        width: 32px;");
document.writeln("        height: 32px;");
document.writeln("        cursor: pointer;");
document.writeln("    }");
document.writeln("</style>");
document.writeln("<script language=\"javascript\" src=\"http://PET.zoosnet.net/JS/LsJS.aspx?siteid=PET86539028&lng=cn\"></script>");
document.writeln("<script language=\"javascript\" src=\"http://apps.bdimg.com/libs/jquery/2.1.4/jquery.js\"></script>");
document.writeln("<div class=\"center\" id=\"center\">");
document.writeln("    <img src=\"http://www.go7758.com/images/swt.png\" onclick=\"window.location.href=\'http://www.go7758.com/swt/\'\">");
document.writeln("    <div class=\"close_btn\"></div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("    var tm=0;");
document.writeln("    $(\'.close_btn\').click(function () {");
document.writeln("        $(\'#center\').fadeOut();");
document.writeln("        clearInterval(tm);");
document.writeln("        tm=setInterval(function () {");
document.writeln("            $(\'#center\').fadeIn();");
document.writeln("        },5000);");
document.writeln("    })");
document.writeln("</script>");